### ISSUE TITLE
how to run django app and qcluster in separate clusters

### ISSUE THREAD

**Issue by AnanyaP-WDW** [django-q2/django-q2#177]
Hi,
I'm using docker-compose to containerize two services, the main app service to queue tasks  and the qcluster service to create qcluter. I'm using sqlite orm as a the borker. It is shared between the two services.

Docker-compose file:
```
version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    build: .
    volumes:
      - dbdata:/app
    networks:
      - db_network
      - web_network
  qcluster:
    container_name: qcluster
    restart: always
    env_file: .env
    command: python manage.py qcluster
    build: .
    volumes:
      - dbdata:/app
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  dbdata: {}
```
 setting.py file:
 ```
Q_CLUSTER = {
    'name': 'mycluster',
    'workers': 4,
    'recycle': 50, # The number of tasks a worker will process before recycling . Useful to release memory resources on a regular basis. Defaults to 500.
    'timeout': 1000, #The number of seconds a worker is allowed to spend on a task before it’s terminated
    'retry': 1200, # The value must be bigger than the time it takes to complete longest task, i.e. timeout must be less than retry value and all tasks must complete in less time than the selected retry time
    'queue_limit': 50,
    'label': 'Django Q2',
    'catch up': False,
    'bulk': 10,
    'orm': 'default',
    'sync': False,
    'ack_failures': True,
    'ack_warning': False,
    'orm_check': True,
}

# cache for django-q --> python manage.py createcachetable
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}
```
The Problem:
It seems that even though the cluster is setup in the qcluster container, It's not accessible/visible in the main app service. Not sure what I'm missing. 

Thanks for you patience.
