### ISSUE TITLE
How to run inside Docker

### ISSUE THREAD

**Issue by paulocoutinhox** [django-q2/django-q2#238]
Hi,

Im trying make on my docker-compose.yml a way to run a worker in the same container of application:

```
services:
  aixdg:
    build: &app-build
      context: aixdg
      dockerfile: Dockerfile
    restart: always
    depends_on: &app-depends-on
      - mysql
    environment: &app-environment
      - DJANGO_SETTINGS_MODULE=pyaa.settings.prod
      - APP_ALLOWED_HOSTS=xyz.com
      - APP_CSRF_TRUSTED_ORIGINS=https://xyz.com
      - APP_PAYMENT_HOST=xyz.com
    volumes:
      - ./aixdg/logs:/app/logs
      - ./aixdg/cache:/app/cache
      - ./aixdg/db:/app/db
      - ./aixdg/media:/app/media
      - ./aixdg/static:/app/static
    ports:
      - "8000:8000"
    command: /app/app-entrypoint.sh

  aixdg-worker:
    build: *app-build
    environment: *app-environment
    depends_on: *app-depends-on
    command: python3 manage.py qcluster
```
